name: Test Rust crate on illumos!
on:
    push:
        paths-ignore:
            - '**.md'
        branches:
            - wip/circleci_illumos

jobs:
  illumos:
  name: illumos test with rust
  runs-on: macos-latest
  steps:
  - uses: actions/checkout@master
  - name: Run cargo test
    uses: papertigers/illumos-vm@main
    with:
      mem: 7168
      prepare: |
        pkg install build-essential
        pkg install ooce/developer/rust
      run: |
        cargo test \
          --manifest-path=openssl/Cargo.toml \
